concertWeb/config/routes.rb
Rails.application.routes.draw do
  root :to => "concerts#index"
  resources :concerts

  get 'concerts/:id/like', to: 'concerts#like'
end

concertWeb/app/models/concert.rb
class Concert < ActiveRecord::Base
	validates :band, 
			  :venue,
			  :city,
			  :date, 
			  :price, 
			  :description, 
			  presence: true
			  
	validates :price, numericality: true
end

concertWeb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

concertWeb/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
	def index
      	@FechaActual = Date.current.year.to_s + "-" + format('%02d', Date.current.month).to_s + "-" + format('%02d', (Date.current.day)).to_s;
        @concerts = Concert.select("id, band, venue, city, date, price, description").where(:date => @FechaActual)
        #@concerts = Concert.all
        
        @DiaSiguiente = Date.current.year.to_s + "-" + format('%02d', Date.current.month).to_s + "-" + format('%02d', (Date.current.day+1)).to_s;
        @DiaFinalMes = Date.current.year.to_s + "-" + format('%02d', Date.current.month).to_s + "-31";
        @concertsRestantesMes = Concert.select("id, band, venue, city, date, price, description").where(date: @DiaSiguiente .. @DiaFinalMes)

        @concertsLikes = Concert.select("id, band, venue, city, date, price, description, likes").order("likes DESC").limit(10)

  end

  def show
      @concerts = Concert.find(params[:id])
  end

  def new
   		@concert = Concert.new
  end

  def edit
  		@concert = Concert.find(params[:id])
	end

  def create
      @concert = Concert.new(concert_params)
      if @concert.save
        redirect_to concert_path(@concert)
      else
        render :new
      end   
  end

  def update
 		@concert = Concert.find(params[:id])
    @concert.update(concert_params)
    if @concert.save
        redirect_to concert_path(@concert)
    else
        render :new
    end
	end

	def destroy
        @concert = Concert.find(params[:id])
        @concert.destroy
        redirect_to root_path
  end

  def like
    @concert = Concert.find(params[:id])
    @concert.likes = @concert.likes + 1;
    @concert.save
     
    @concerts = Concert.find(params[:id])
    render :show   
  end

  	private
    def concert_params
        params.require(:concert).permit(:band, :venue, :city, :date, :price, :description)
    end
end

concertWeb/app/helpers/application_helper.rb
module ApplicationHelper
end

concertWeb/app/helpers/concerts_helper.rb
module ConcertsHelper
end

concertWeb/app/views/concerts/edit.html.erb
<head>
  <style type="text/css">

  a:link {   
 
  text-decoration:none;   

  }   

  </style>

</head>

<header>
    <img class="cabeza" src="/images/manos.jpg"/>
</header>

<h3>Editing a concert</h3>

<%= form_for @concert do |f| %>
 
 <% if @concert.errors.any? %>
   <h2>Errors:</h2>
   <ul>
     <% @concert.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
 <% end %>


  <p>
    <%= f.label :band %><br>
    <%= f.text_field :band %>
  </p>

  <p>
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<p class="BotonBack"><%= link_to 'Back', concerts_path%></p>

<footer>
  <hr>
  <p>Página web creada por: Manu Ábalos, Alfredo García, Jose Luis Cantalejo y Pablo Iriarte</p>
  <p>-30 de Abril de 2015-</p>
</footer>

concertWeb/app/views/concerts/index.html.erb
<head>
	<style type="text/css">

	a:link {   
 
 	text-decoration:none;   

	}   

	</style>

</head>

<header>
	<img class="cabeza" src="/images/manos.jpg"/>
	<p class="primerafrase">Here you cand find the best concerts and festivals around Europe</p>
</header>

<article>

	<h1>Concerts today:</h1>
	<% @concerts.each do |concert|%>
		<div><p class="BotonNuevo"><%= link_to concert.band, concert_path(concert)%></p> 
			<%= concert.date %>
			|| <%= link_to 'Destroy', concert_path(concert), method: :delete, data: { confirm: 'Are you sure?' } %>
			|| <%= link_to 'Edit', edit_concert_path(concert) %>
		<hr>
		</div>
	<% end %>

	<p class="BotonNuevo">
	    <%= link_to 'Nuevo concierto', new_concert_path %>
	</p>
	
	<hr>
	<h1>Top 10 likes concerts:</h1>
	<% @concertsLikes.each do |concertsLikes|%>
		<div><p class="BotonNuevo"><%= link_to concertsLikes.band, concert_path(concertsLikes)%></p> 
			Total likes: <%= concertsLikes.likes %>
		<hr>
		</div>
	<% end %>



</article>



<aside>
		<h1> Later this month... </h1>
		<% @concertsRestantesMes.each do |concertsRestantesMes|%>
		<div>
			<p class="BotonNuevo">
				<%= link_to concertsRestantesMes.band, concert_path(concertsRestantesMes)%>
			</p>
			<%= concertsRestantesMes.date %>
			<hr>
		</div>
	<% end %>
</aside>

<footer class="indexfooter">
	<hr>
	<p>Página web creada por: Manu Ábalos, Alfredo García, Jose Luis Cantalejo y Pablo Iriarte</p>
	<p>-30 de Abril de 2015-</p>
</footer>

concertWeb/app/views/concerts/new.html.erb
<head>
  <style type="text/css">

  a:link {   
 
  text-decoration:none;   

  }   

  </style>

</head>

<header>
    <img class="cabeza" src="/images/manos.jpg"/>
</header>

<h3>
  Create a new concert
</h3>

<%= form_for @concert do |f| %>
 
 <% if @concert.errors.any? %>
   <h2>Errors:</h2>
   <ul>
     <% @concert.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
 <% end %>
  
<p>
  <%= f.label :band %><br>
  <%= f.text_field :band %>
</p>

<p>
  <%= f.label :venue %><br>
  <%= f.text_field :venue %>
</p>

<p>
  <%= f.label :city %><br>
  <%= f.text_field :city %>
</p>

<p>
  <%= f.label :date %><br>
  <%= f.text_field :date %>
</p>

<p>
  <%= f.label :price %><br>
  <%= f.text_field :price %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

<p>
  <p class="BotonBack"><%= link_to 'Back', concerts_path %></p>
</p>

<footer>
  <hr>
  <p>Página web creada por: Manu Ábalos, Alfredo García, Jose Luis Cantalejo y Pablo Iriarte</p>
  <p>-30 de Abril de 2015-</p>
</footer>

concertWeb/app/views/concerts/show.html.erb
<head>
	<style type="text/css">

	a:link {   
 
 	text-decoration:none;   

	}   

	</style>

</head>

<header>
	<img class="cabeza" src="/images/manos.jpg"/>
</header>

<h3>
	<strong>Band:</strong>
	<%= @concerts.band %>
</h3>

<nav>
<p>
	<strong>Venue:</strong>
	<%= @concerts.venue %>

	<strong>City:</strong>
	<%= @concerts.city %>

	<strong>Date:</strong>
	<%= @concerts.date %>

	<strong>Price:</strong>
	<%= @concerts.price %>

	<strong>Likes:</strong>
	<%= @concerts.likes %>
</p>

<p class="Explicacion">
	<strong>Description:</strong>
	<%= @concerts.description %>
</p>

<p class="BotonBack"><%= link_to 'Like!', :controller => :concerts, :action => :like %></p>
<p class="BotonBack"><%= link_to 'Back', concerts_path %></p>

</nav>



<footer>
	<hr>
	<p>Página web creada por: Manu Ábalos, Alfredo García, Jose Luis Cantalejo y Pablo Iriarte</p>
	<p>-30 de Abril de 2015-</p>
</footer>

concertWeb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>